import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const trpcTest = trpc.product.getAll.useQuery(20);
  const trpcCategory = trpc.category.getOneCategory.useQuery("Kindle");
  // const trpcTest2 = trpc.product.getOne.useQuery(
  //   "Licensed Handcrafted Wooden Gloves"
  // );
  console.log(trpcCategory.data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex w-screen gap-4 overflow-x-scroll">
          {trpcTest.data?.map((el) => {
            return (
              <div className="flex flex-col text-xl text-white" key={el.id}>
                <span>{el.id}</span>
                <span>{el.title}</span>
                <Image alt={el.title} src={el.image} width={200} height={200} />
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
